compressionLevel: mixed

defaultSemverRangePrefix: ""

nodeLinker: pnpm

packageExtensions:
  "@typescript-eslint/type-utils@*":
    peerDependencies:
      eslint: "*"
  "@typescript-eslint/utils@*":
    peerDependencies:
      typescript: "*"
  "@stylistic/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
  "eslint-plugin-perfectionist@*":
    peerDependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-4.4.1.cjs