compressionLevel: mixed

defaultSemverRangePrefix: ""

nodeLinker: pnpm

packageExtensions:
  "@stylistic/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
  "eslint-plugin-perfectionist@*":
    peerDependencies:
      typescript: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
