name: eslint
on: [ push ]
jobs:
  eslint:
    name: runner / eslint
    # runs-on: [self-hosted, linux, x64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: yarn
      - run: yarn install
      - run: yarn run eslint src
